#' SQL for inserting missing values
#'
#' @param conflict_target A conflict target generated by [sql_unique_cols()]
#' or [sql_constraint()].
#' @inheritParams sql_insert
#' @inheritParams sql_update
#'
#' @return An SQL query.
#' @export
#' @examples
#' DBI::dbWriteTable(con, "dbtools_mtcars", mtcars[1, ], overwrite = TRUE)
#' DBI::dbExecute(
#'   con,
#'   'ALTER TABLE dbtools_mtcars
#'   ADD CONSTRAINT unique_const
#'   UNIQUE ("mpg", "cyl");'
#' )
#' sql_insert_missing(
#'   data = mtcars[c(1, 3), ],
#'   table = "dbtools_mtcars",
#'   con = con,
#'   conflict_target = sql_unique_cols("mpg", "cyl"),
#'   returning = SQL("*"),
#'   return_all = TRUE
#' )
sql_insert_missing <- function(data,
                               table,
                               con,
                               conflict_target = NULL,
                               insert_cols = NULL,
                               returning = NULL,
                               return_all = FALSE) {
  sql_insert(
    data = data,
    table = table,
    con = con,
    conflict = sql_do_nothing(conflict_target),
    insert_cols = insert_cols,
    returning = returning,
    return_all = return_all
  )
}


#' SQL for inserting missing values
#'
#' @inheritParams sql_insert_missing
#' @inheritParams sql_update
#'
#' @export
sql_upsert <- function(data,
                       table,
                       con,
                       conflict_target,
                       update,
                       insert_cols = NULL,
                       returning = NULL) {
  sql_insert(
    data = data,
    table = table,
    con = con,
    conflict = sql_do_update(conflict_target, update),
    insert_cols = insert_cols,
    returning = returning
  )
}
